server:
  port: 8280
spring:
  application:
    # the name of kubernetes service associated to k8s-aepc-ms-config-pod
    name: k8s-aepc-ms-config-service
  main:
    banner-mode: off
  config:
    activate:
      on-profile: develop
  cloud:
    config:
      server:
        git:
          uri: https://github.com/placidenduwayo1/config-files-center.git
          default-label: main
          search-paths: for-k8s-aepc-back-project
#          default message
  message: welcome to spring cloud config service

