server:
  port: 8380
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/placidenduwayo1/K8s-AEPC-ms-config-centralisation.git
          default-label: main
  main:
    banner-mode: off
  message: configuration server default profile is working
